### ISSUE TITLE
Problem Compiling for any ESP8266

### ISSUE THREAD

**Issue by Seb-Sab** [dushyantahuja/IPGeolocation#2]
Hi Dushyantahuja,

First of all I want to thank you developping this Library that will be very usefull for one of my project.
I am fairely new in Arduino and I am facing a problem once compiling sketch using your Lib.

Here enclosed the errorI am getting :

Compiling library "arduino_40926"
"C:\\Users\\sebsa\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\2.5.0-3-20ed2b9/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\\Users\\sebsa\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.5.2/tools/sdk/include" "-IC:\\Users\\sebsa\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.5.2/tools/sdk/lwip2/include" "-IC:\\Users\\sebsa\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.5.2/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\\Users\\sebsa\\AppData\\Local\\Temp\\arduino_build_902199/core" -c -Wall -Wextra -Os -g -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -fno-exceptions -DNONOSDK221=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10810 -DARDUINO_ESP8266_WEMOS_D1R1 -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_WEMOS_D1R1\"" -DFLASHMODE_DIO -DESP8266 "-IC:\\Users\\sebsa\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.5.2\\cores\\esp8266" "-IC:\\Users\\sebsa\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.5.2\\variants\\d1" "-IC:\\Users\\sebsa\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.5.2\\libraries\\ESP8266WiFi\\src" "-IC:\\Users\\sebsa\\Dropbox\\Perso\\Projets\\Arduino\\libraries\\ArduinoJson-5.13.4\\src" "-IC:\\Users\\sebsa\\Dropbox\\Perso\\Projets\\Arduino\\libraries\\arduino_40926\\src" "C:\\Users\\sebsa\\Dropbox\\Perso\\Projets\\Arduino\\libraries\\arduino_40926\\src\\IPGeolocation.cpp" -o "C:\\Users\\sebsa\\AppData\\Local\\Temp\\arduino_build_902199\\libraries\\arduino_40926\\IPGeolocation.cpp.o"
C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp: In member function 'void IPGeolocation::updateStatus(IPGeo*)':

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:65:3: error: 'DynamicJsonDocument' was not declared in this scope

   DynamicJsonDocument doc(capacity);

   ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:65:23: error: expected ';' before 'doc'

   DynamicJsonDocument doc(capacity);

                       ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:67:19: error: 'doc' was not declared in this scope

   deserializeJson(doc, _Response);

                   ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:67:33: error: 'deserializeJson' was not declared in this scope

   deserializeJson(doc, _Response);

                                 ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:68:36: error: expected primary-expression before '>' token

   I->tz = doc["timezone"].as<String>();

                                    ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:68:38: error: expected primary-expression before ')' token

   I->tz = doc["timezone"].as<String>();

                                      ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:70:43: error: expected primary-expression before 'int'

   int dst_savings = doc["dst_savings"].as<int>();

                                           ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:73:52: error: expected primary-expression before '>' token

   I->country = doc["geo"]["country_name"].as<String>();

                                                    ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:73:54: error: expected primary-expression before ')' token

   I->country = doc["geo"]["country_name"].as<String>();

                                                      ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:74:58: error: expected primary-expression before '>' token

   I->country_code = doc["geo"]["country_code2"].as<String>();

                                                          ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:74:60: error: expected primary-expression before ')' token

   I->country_code = doc["geo"]["country_code2"].as<String>();

                                                            ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:75:41: error: expected primary-expression before '>' token

   I->city = doc["geo"]["city"].as<String>();

                                         ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:75:43: error: expected primary-expression before ')' token

   I->city = doc["geo"]["city"].as<String>();

                                           ^

C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926\src\IPGeolocation.cpp:22:16: warning: unused variable 'capacity' [-Wunused-variable]

   const size_t capacity = JSON_OBJECT_SIZE(10) + JSON_OBJECT_SIZE(17) + 580;

                ^

Multiple libraries were found for "ESP8266WiFi.h"
 Used: C:\Users\sebsa\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266WiFi
Multiple libraries were found for "ArduinoJson.h"
 Used: C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\ArduinoJson-5.13.4
 Not used: C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_358418
Multiple libraries were found for "IPGeolocation.h"
 Used: C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\sebsa\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266WiFi 
Using library ArduinoJson-5.13.4 at version 5.13.4 in folder: C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\ArduinoJson-5.13.4 
Using library arduino_40926 at version 2.1.3 in folder: C:\Users\sebsa\Dropbox\Perso\Projets\Arduino\libraries\arduino_40926 
exit status 1
Error compiling for board WeMos D1 R1.

I double check using other board,I reinstall the last version of your LIb using the Library Manager with Arduino... but it is not solving the problem.
I am very sorry as it might seen a low level mistake, but I am desperate solving it .
Thank you in Advance for your help.

Merry Christmas and Happy New Year.
Regards
Sebastien

**Comment by dushyantahuja** [comment]
You also need to install the ArduinoJSON library. Install using the library
manager - and it should work.
