### ISSUE TITLE
Functions do not catch faulty states

### ISSUE THREAD

**Issue by aly-fly** [dushyantahuja/IPGeolocation#4]
Main function "void IPGeolocation::updateStatus(IPGeo *I)" does not catch any faulty states, for example:

- connection timeout
- number of retries run out (continues processing non-existing data even after timeout)
- timeout while collecting data from server (stuck in a continuous loop, blocks the application)
- error while parsing received data (can return garbage)
- checking that received data is in expected ranges (can return invalid values as a "good" result)
- etc.

Currently I have to copy library to my project and make all necessary changes to catch all those possible errors and make suitable action upon error (for example returning value "false" if unsuccessful / data is not valid). 
This way library is disconnected from any future updates...

**Comment by dushyantahuja** [comment]
If you want to put a pull request, I'd be happy to include.

Regards
